### ISSUE TITLE
conflict in syntax for PHITS and MCNP 

### ISSUE THREAD

**Issue by Rafmigz** [GordoNice/phits_sublime_support#1]
Hi! I was trying to add the [MCNP syntax](https://github.com/danyalturkoglu/MCNP-syntax-highlighting) to my Sublime Text 3 , with existing PHITS syntax. After adding the MCNP syntax, it does not appear in the language options.

Now, I tried to remove this PHITS syntax, and the MCNP syntax is now appearing. 

I can't understand why is there a conflict between the two syntaxes. Whereas is it should be independent to one another.

**Comment by GordoNice** [comment]
Hello! I don't see any issue, I just copied `mcnp.sublime-syntax` in the `C:\Users\{username}\AppData\Roaming\Sublime Text 3\Packages\User` where `{username}` is my user name in windows. And now I can see both `mcnp` and `PHITS input` options for highlighting in the right bottom corner of sublime.

So, I have a guess, that you just not reloaded sublime after adding MCNP syntax. You can try to place all the files under `C:\Users\{username}\AppData\Roaming\Sublime Text 3\Packages\User` or `~/.config/sublime-text-3/Packages/User` for linux once again and reload sublime. But there is no conflict, as you pointed, they are independent.

Please let me know if it's fine or not. If not, please describe more explicitly your steps. 

Regards,
Ivan

**Comment by GordoNice** [comment]
Dear @Rafmigz!
Please feel free to reopen the issue if the problem remains.
